// Note: Main root file...!

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Note: MDB library integration...!
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";

// NoteL Importing required components...!
import Navbar from '@/components/navigation/navigation';

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;